[project]
<<<<<<< HEAD
name = "games_project_svirko"
version = "0.2.0"
description = "Проект с играми для практической работы"
requires-python = ">=3.8"
dependencies = [
    "prompt>=0.4.1",
]
=======
name = "games-project-svirko"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
>>>>>>> dd74827 (Add brain-calc game)

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

<<<<<<< HEAD
[project.scripts]
vd-games = "VD_games.scripts.VD_main:main"

[tool.hatch.build.targets.wheel]
packages = ["VD_games"]
=======
[tool.hatch.build.targets.wheel]
packages = ["VD_games"]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]

[project.scripts]
VD-even = "VD_games.scripts.VD_even:play_even_game"
VD-games = "VD_games.scripts.VD_main:main"
brain-calc = "scripts.brain_calc:main"


>>>>>>> dd74827 (Add brain-calc game)
